version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tripplanner-postgres
    environment:
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: postgres        
      POSTGRES_DB: tripplanner       
    ports:
      - "5432:5432"                  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4           
    container_name: tripplanner-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tripplanner.com    
      PGADMIN_DEFAULT_PASSWORD: admin123             
    ports:
      - "5050:80"                
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: tripplanner-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: tripplanner-auth
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/tripplanner
      - SECRET_KEY= # тут ключ
      - ALGORITHM=HS256
      - NOTIFICATION_SERVICE_URL=http://notification-service:8000
      - FRONTEND_BASE_URL=http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
      notification-service:
        condition: service_started
    volumes:
      - ./auth-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: tripplanner-user
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/tripplanner
      - AUTH_SERVICE_URL=http://auth-service:8000
    depends_on:
      - postgres
      - auth-service
    volumes:
      - ./user-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  notification-service:
    build: ./notification-service
    container_name: tripplanner-notification
    ports:
      - "8007:8000"
    environment:
      - SMTP_HOST=
      - SMTP_PORT=587
      - SMTP_USER=
      - SMTP_PASSWORD=
      - FROM_EMAIL=noreply@tripplanner.local
    volumes:
      - ./notification-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  trip-service:
    build: ./trip-service
    container_name: tripplanner-trip
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/tripplanner
      - AUTH_SERVICE_URL=http://auth-service:8000
      - NOTIFICATION_SERVICE_URL=http://notification-service:8000
      - SECRET_KEY= # тут ключ
      - ALGORITHM=HS256
    depends_on:
      - auth-service
      - notification-service
      - postgres
    volumes:
      - ./trip-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  voting-service:
    build: ./voting-service
    container_name: tripplanner-voting
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/tripplanner
      - REDIS_URL=redis://redis:6379/0
      - AUTH_SERVICE_URL=http://auth-service:8000
      - TRIP_SERVICE_URL=http://trip-service:8000
      - NOTIFICATION_SERVICE_URL=http://notification-service:8000
    depends_on:
      - auth-service
      - trip-service
      - notification-service
      - postgres
      - redis
    volumes:
      - ./voting-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  budget-service:
    build: ./budget-service
    container_name: tripplanner-budget
    ports:
      - "8005:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/tripplanner
      - AUTH_SERVICE_URL=http://auth-service:8000
      - TRIP_SERVICE_URL=http://trip-service:8000
    depends_on:
      - auth-service
      - trip-service
      - postgres
    volumes:
      - ./budget-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  chat-service:
    build: ./chat-service
    container_name: tripplanner-chat
    ports:
      - "8006:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/tripplanner
      - AUTH_SERVICE_URL=http://auth-service:8000
      - TRIP_SERVICE_URL=http://trip-service:8000
      - NOTIFICATION_SERVICE_URL=http://notification-service:8000
    depends_on:
      - auth-service
      - trip-service
      - notification-service
      - postgres
    volumes:
      - ./chat-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  app-network:
    driver: bridge